redis:
  address: '127.0.0.1'
  port: 6379
  password: '6ytqYNW4kUeZxrEpX0E6vgjgtmLALL/Bvs6Tpv5Tkscr3MjumCOZXB9YVXLfTYKhsVAOaaKt8y/eAy/6PYIiAL02dqgaU/NQmk4MkyReo/CJ8BM0Dk74Eg8sSZDCqsVQwnMDiLTZD/xT+gys2K4a1mlnIBJdKLBlSW2tqGCBkW0='
disable-weather: true
default-money: 15000.0
player-joins: 0
server-prefix: '&8[&e&lMineage&6&lPVP&8] '
first-join-message: '&8[&e&lMineage&6&lPVP&8] &eWelcome our {player} &f(#{join-times})'
broadcast-prefix: '&8[&c&lBroadcast&8] &f'
motd-message:
  - '&8&l【&fWelcome to &3Mineage&7PvP&8&l】'
  - '&7&lStore&8&l: &3https://store.mineagepvp.com/'
  - '&7&lDiscord&8&l: &3https://discord.gg/rdC6hc3'
  - '&7Use &3/kit &7& &3/wild &7to get started'
spawn:
  world: 'world'
  x: 0.5
  y: 122
  z: 0.5